development:
  adapter: postgresql
  encoding: unicode
  database: twitter_bot_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: twitter_bot_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: twitter_bot_production
  pool: 5
  username: postgres
  password: